[Variables]
;== Circle Settings ==;
AllCircleRadius=130
AllMovingSpeed=5
AllDistanceApart=4
AllUpdate=20

;== Text Settings ==;
CenteringValueTitle=-30
CenteringValueInfo=-30
TitleFontSize=30
InfoFontSize=30
TitleFontFace=Segoe UI Light
InfoFontFace=Segoe UI Light

;== Drives ==;
Drive1=C
Drive2=G
Drive3=E
Drive4=F

;== Color ==;
AllColor1=64,64,64
AllColor2=120,120,120
InfoFontColor=0,0,0
TitleFontColor=0,0,0
